version: '3.8'
services:
  carla-control:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    working_dir: /app